from Game import Game
from Player import Player

new_player1 = Player("Jkans")

new_player2 = Player("Troller")

new_game = Game(new_player1, new_player2)
new_game_2 = Game(Player('Tozzi'), Player('stetson'))


assert new_game.game_players[1].my_cards["V0"].card.is_virus()


def match_1(game):
    game_player_0 = game.game_players[0]
    assert game_player_0.do_put_card_on_setup(1, 1, "V0")
    assert game_player_0.do_put_card_on_setup(2, 1, "V1")
    assert game_player_0.do_put_card_on_setup(3, 1, "V2")
    assert game_player_0.do_put_card_on_setup(4, 2, "V3")
    assert game_player_0.do_put_card_on_setup(5, 2, "L0")
    assert game_player_0.do_put_card_on_setup(6, 1, "L1")
    assert game_player_0.do_put_card_on_setup(7, 1, "L2")
    assert game_player_0.do_put_card_on_setup(8, 1, "L3")
    game_player_1 = game.game_players[1]
    assert game_player_1.do_put_card_on_setup(1, 8, "V0")
    assert game_player_1.do_put_card_on_setup(2, 8, "V1")
    assert game_player_1.do_put_card_on_setup(3, 8, "V2")
    assert game_player_1.do_put_card_on_setup(4, 7, "V3")
    assert game_player_1.do_put_card_on_setup(5, 7, "L0")
    assert game_player_1.do_put_card_on_setup(6, 8, "L1")
    assert game_player_1.do_put_card_on_setup(7, 8, "L2")
    assert game_player_1.do_put_card_on_setup(8, 8, "L3")
    assert len(game.game_players) == 2
    print(game.to_string())
    game.start_game()
    game_player_0.card_move("V3", "N")
    game_player_1.card_move("V3", "N")
    game_player_0.card_move("V3", "N")
    game_player_1.card_move("V3", "N")
    game_player_0.card_move("V3", "N")
    print(game.to_string())
    game_player_1.use_virus_checker(4, 5)
    game_player_0.place_line_boost(4, 5)
    # game_player_0.card_move("L3", "N")
    game_player_1.install_firewall(2, 3)
    game_player_0.use_404_not_found("V3", "L0", True)
    # print(new_game.started, len(game_player_0.stack_area.links), len(game_player_1.stack_area.viruses))
    game_player_1.card_move("V1", "N")
    game_player_0.card_move("L0", "N", "E")
    game_player_1.card_move("L0", "N")
    print(game.to_string())
    assert game_player_0.line_boosted is None
    assert game.board.square_at(6, 1).player_card.card.is_link()
    game_player_0.place_line_boost(6, 1)
    # print(game_player_0.line_boosted.card_name)
    # print(new_game.turn, game_player_1.game_player_index)
    game_player_1.card_move("L0", "N")
    game_player_0.card_move("L1", "N", "N")
    game_player_1.card_move("L0", "N")
    game_player_0.card_move("L1", "N", "N")
    game_player_1.card_move("L0", "N")
    game_player_0.card_move("L1", "N", "N")
    game_player_1.card_move("L0", "N")
    game_player_0.card_move("L1", "W", "W")
    game_player_1.card_move("L0", "N")
    print(game.to_string())
    game_player_0.card_move("L1", "N", "F")
    game_player_1.card_move("L0", "F")
    game_player_0.install_firewall(2, 6)
    game_player_1.uninstall_firewall(2, 3)
    game_player_0.card_move("L2", "N")
    game_player_1.place_line_boost(6, 8)
    game_player_0.place_line_boost(7, 2)
    game_player_1.card_move("L1", "N", "N")
    game_player_0.card_move("L2", "N", "W")
    game_player_1.card_move("L1", "N", "N")
    game_player_0.use_virus_checker(8, 8)
    game_player_1.card_move("L1", "N")
    game_player_0.card_move("L3", "W")
    game_player_1.card_move("L1", "N", "N")
    game_player_0.card_move("V0", "N")
    # game_player_1.card_move("L1", "E", "F")
    game_player_1.detach_line_boost(6, 1)
    game_player_0.card_move("V0", "N")
    game_player_1.card_move("L1", "W")
    print(game.to_string())


match_1(new_game)
match_1(new_game_2)
